///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording4 recording.
    /// </summary>
    [TestModule("9efbc8d8-2627-4b40-b069-79343ee60ee3", ModuleType.Recording, 1)]
    public partial class Recording4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDemoAppRepository repository.
        /// </summary>
        public static RxDemoAppRepository repo = RxDemoAppRepository.Instance;

        static Recording4 instance = new Recording4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.UIElementTestArea' at 51;14.", repo.RxMainFrame.UIElementTestAreaInfo, new RecordItemIndex(0));
            repo.RxMainFrame.UIElementTestArea.Click("51;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.RdbRedLight' at 9;6.", repo.RxMainFrame.RxTabUIElements.RdbRedLightInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabUIElements.RdbRedLight.Click("9;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.RxTabUIElements.PnlColourPanel'.", repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo, new RecordItemIndex(2));
            Validate.Exists(repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.RdbGreenLight' at 10;10.", repo.RxMainFrame.RxTabUIElements.RdbGreenLightInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabUIElements.RdbGreenLight.Click("10;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.RxTabUIElements.PnlColourPanel'.", repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo, new RecordItemIndex(4));
            Validate.Exists(repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 8;7.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(11));
            repo.RxMainFrame.RxTabUIElements.Down.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Hands-on application topics') on item 'RxMainFrame.RxTabUIElements.HandsOnApplicationTopics'.", repo.RxMainFrame.RxTabUIElements.HandsOnApplicationTopicsInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabUIElements.HandsOnApplicationTopicsInfo, "Text", "Hands-on application topics");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabUIElements.RanorexStudioFundamentals' at 105;3.", repo.RxMainFrame.RxTabUIElements.RanorexStudioFundamentalsInfo, new RecordItemIndex(13));
            repo.RxMainFrame.RxTabUIElements.RanorexStudioFundamentals.DoubleClick("105;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Ranorex Recorder') on item 'RxMainFrame.RxTabUIElements.RanorexRecorder'.", repo.RxMainFrame.RxTabUIElements.RanorexRecorderInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabUIElements.RanorexRecorderInfo, "Text", "Ranorex Recorder");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.LineDown' at 11;12.", repo.RxMainFrame.RxTabUIElements.LineDownInfo, new RecordItemIndex(15));
            repo.RxMainFrame.RxTabUIElements.LineDown.Click("11;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.DepartmentRow7' at 28;6.", repo.RxMainFrame.RxTabUIElements.DepartmentRow7Info, new RecordItemIndex(16));
            repo.RxMainFrame.RxTabUIElements.DepartmentRow7.Click("28;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Testing') on item 'RxMainFrame.RxTabUIElements.DepartmentRow7'.", repo.RxMainFrame.RxTabUIElements.DepartmentRow7Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabUIElements.DepartmentRow7Info, "Text", "Testing");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
