///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemoApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDemoAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ff976536-8081-48ad-863e-a2c848594ae3")]
    public partial class RxDemoAppRepository : RepoGenBaseFolder
    {
        static RxDemoAppRepository instance = new RxDemoAppRepository();
        RxDemoAppRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        RxDemoAppRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the RxDemoAppRepository element repository.
        /// </summary>
        [RepositoryFolder("ff976536-8081-48ad-863e-a2c848594ae3")]
        public static RxDemoAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDemoAppRepository() 
            : base("RxDemoAppRepository", "/", null, 0, false, "ff976536-8081-48ad-863e-a2c848594ae3", ".\\RepositoryImages\\RxDemoAppRepositoryff976536.rximgres")
        {
            _rxmainframe = new RxDemoAppRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new RxDemoAppRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ff976536-8081-48ad-863e-a2c848594ae3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("58e51b35-9e2b-47c5-8131-0193e16da259")]
        public virtual RxDemoAppRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("63c0b7d8-afc0-427c-bfea-2b74a03c1720")]
        public virtual RxDemoAppRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDemoAppRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("58e51b35-9e2b-47c5-8131-0193e16da259")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RxDemoAppRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            RxDemoAppRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RxDemoAppRepositoryFolders.RxTabImageBasedFolder _rxtabimagebased;
            RxDemoAppRepositoryFolders.RxTabUIElementsFolder _rxtabuielements;
            RxDemoAppRepositoryFolders.RxTabUploadFolder _rxtabupload;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _imagebasedautomationInfo;
            RepoItemInfo _uielementtestareaInfo;
            RepoItemInfo _uploadtestingInfo;
            RepoItemInfo _dynamicidsInfo;
            RepoItemInfo _chkshowdynamicidInfo;
            Img9jlc98mqhm3nc7drInfoClass _img9jlc98mqhm3nc7drInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _introductionInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "58e51b35-9e2b-47c5-8131-0193e16da259", "")
            {
                _rxtabintroduction = new RxDemoAppRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabstandard = new RxDemoAppRepositoryFolders.RxTabStandardFolder(this);
                _rxtabimagebased = new RxDemoAppRepositoryFolders.RxTabImageBasedFolder(this);
                _rxtabuielements = new RxDemoAppRepositoryFolders.RxTabUIElementsFolder(this);
                _rxtabupload = new RxDemoAppRepositoryFolders.RxTabUploadFolder(this);
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@automationid='TitleBar']", "titlebar[@automationid='TitleBar']", 30000, null, "341ecb3f-e01c-4861-ad77-112e201672be");
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "643a0575-86b6-4760-a218-d0c7a90165d1");
                _imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", "?/?/tabpage[@accessiblename='Image-based automation']", 30000, null, "ef2b0064-13da-4843-a724-7716f83d7781");
                _uielementtestareaInfo = new RepoItemInfo(this, "UIElementTestArea", "?/?/tabpage[@accessiblename='UI-element test area']", "?/?/tabpage[@accessiblename='UI-element test area']", 30000, null, "87ac8092-b4af-40e9-b052-0804e7cf54c6");
                _uploadtestingInfo = new RepoItemInfo(this, "UploadTesting", "?/?/tabpage[@accessiblename='Upload testing']", "?/?/tabpage[@accessiblename='Upload testing']", 30000, null, "1ccf3c44-e281-4424-84ab-afc517e16f32");
                _dynamicidsInfo = new RepoItemInfo(this, "DynamicIDs", "?/?/tabpage[@accessiblename='Dynamic IDs']", "?/?/tabpage[@accessiblename='Dynamic IDs']", 30000, null, "f7ebd4fb-b566-4aac-a5a8-7f154fcbc72e");
                _chkshowdynamicidInfo = new RepoItemInfo(this, "ChkShowDynamicID", ".//checkbox[@controlname='chkShowDynamicID']", ".//checkbox[@controlname='chkShowDynamicID']", 30000, null, "07bb1cef-71e2-4506-9948-777fcae30047");
                _img9jlc98mqhm3nc7drInfo = new Img9jlc98mqhm3nc7drInfoClass(this);
                _textInfo = new RepoItemInfo(this, "Text", ".//text[@controlname='txtBoxID']/text[@accessiblerole='Text']", ".//text[@controlname='txtBoxID']/text[@accessiblerole='Text']", 30000, null, "60dc35c3-c24c-4020-801e-23d01946be57");
                _introductionInfo = new RepoItemInfo(this, "Introduction", "?/?/tabpage[@accessiblename='Introduction']", "?/?/tabpage[@accessiblename='Introduction']", 30000, null, "0c4e9ea1-23f1-4377-9998-66c67ffac385");
            }

            /// <summary>
            /// The Img9jlc98mqhm3nc7drInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("d9015894-3bcd-44fd-808d-28ebe491615a")]
            public class Img9jlc98mqhm3nc7drInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Img9jlc98mqhm3nc7drInfoClass class constructor.
                /// </summary>
                public Img9jlc98mqhm3nc7drInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Img9jlc98mqhm3nc7dr", ".//picture[@controlname='img_9jlc98mqhm3nc7dr']", 30000, null, "d9015894-3bcd-44fd-808d-28ebe491615a")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("756c2b12-a6ea-423e-9f83-5acf6b93c572")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("756c2b12-a6ea-423e-9f83-5acf6b93c572");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("756c2b12-a6ea-423e-9f83-5acf6b93c572")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("756c2b12-a6ea-423e-9f83-5acf6b93c572", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("58e51b35-9e2b-47c5-8131-0193e16da259")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("58e51b35-9e2b-47c5-8131-0193e16da259")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("341ecb3f-e01c-4861-ad77-112e201672be")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("341ecb3f-e01c-4861-ad77-112e201672be")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("643a0575-86b6-4760-a218-d0c7a90165d1")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("643a0575-86b6-4760-a218-d0c7a90165d1")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("ef2b0064-13da-4843-a724-7716f83d7781")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("ef2b0064-13da-4843-a724-7716f83d7781")]
            public virtual RepoItemInfo ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The UIElementTestArea item.
            /// </summary>
            [RepositoryItem("87ac8092-b4af-40e9-b052-0804e7cf54c6")]
            public virtual Ranorex.TabPage UIElementTestArea
            {
                get
                {
                    return _uielementtestareaInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The UIElementTestArea item info.
            /// </summary>
            [RepositoryItemInfo("87ac8092-b4af-40e9-b052-0804e7cf54c6")]
            public virtual RepoItemInfo UIElementTestAreaInfo
            {
                get
                {
                    return _uielementtestareaInfo;
                }
            }

            /// <summary>
            /// The UploadTesting item.
            /// </summary>
            [RepositoryItem("1ccf3c44-e281-4424-84ab-afc517e16f32")]
            public virtual Ranorex.TabPage UploadTesting
            {
                get
                {
                    return _uploadtestingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The UploadTesting item info.
            /// </summary>
            [RepositoryItemInfo("1ccf3c44-e281-4424-84ab-afc517e16f32")]
            public virtual RepoItemInfo UploadTestingInfo
            {
                get
                {
                    return _uploadtestingInfo;
                }
            }

            /// <summary>
            /// The DynamicIDs item.
            /// </summary>
            [RepositoryItem("f7ebd4fb-b566-4aac-a5a8-7f154fcbc72e")]
            public virtual Ranorex.TabPage DynamicIDs
            {
                get
                {
                    return _dynamicidsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The DynamicIDs item info.
            /// </summary>
            [RepositoryItemInfo("f7ebd4fb-b566-4aac-a5a8-7f154fcbc72e")]
            public virtual RepoItemInfo DynamicIDsInfo
            {
                get
                {
                    return _dynamicidsInfo;
                }
            }

            /// <summary>
            /// The ChkShowDynamicID item.
            /// </summary>
            [RepositoryItem("07bb1cef-71e2-4506-9948-777fcae30047")]
            public virtual Ranorex.CheckBox ChkShowDynamicID
            {
                get
                {
                    return _chkshowdynamicidInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowDynamicID item info.
            /// </summary>
            [RepositoryItemInfo("07bb1cef-71e2-4506-9948-777fcae30047")]
            public virtual RepoItemInfo ChkShowDynamicIDInfo
            {
                get
                {
                    return _chkshowdynamicidInfo;
                }
            }

            /// <summary>
            /// The Img9jlc98mqhm3nc7dr item.
            /// </summary>
            [RepositoryItem("d9015894-3bcd-44fd-808d-28ebe491615a")]
            public virtual Ranorex.Picture Img9jlc98mqhm3nc7dr
            {
                get
                {
                    return _img9jlc98mqhm3nc7drInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Img9jlc98mqhm3nc7dr item info.
            /// </summary>
            [RepositoryItemInfo("d9015894-3bcd-44fd-808d-28ebe491615a")]
            public virtual Img9jlc98mqhm3nc7drInfoClass Img9jlc98mqhm3nc7drInfo
            {
                get
                {
                    return _img9jlc98mqhm3nc7drInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("60dc35c3-c24c-4020-801e-23d01946be57")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("60dc35c3-c24c-4020-801e-23d01946be57")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Introduction item.
            /// </summary>
            [RepositoryItem("0c4e9ea1-23f1-4377-9998-66c67ffac385")]
            public virtual Ranorex.TabPage Introduction
            {
                get
                {
                    return _introductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Introduction item info.
            /// </summary>
            [RepositoryItemInfo("0c4e9ea1-23f1-4377-9998-66c67ffac385")]
            public virtual RepoItemInfo IntroductionInfo
            {
                get
                {
                    return _introductionInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("8e93b5e8-cb7a-4017-9262-1efe762e9148")]
            public virtual RxDemoAppRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("794cc092-b05f-4699-ba2e-d58d3f1456b3")]
            public virtual RxDemoAppRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }

            /// <summary>
            /// The RxTabImageBased folder.
            /// </summary>
            [RepositoryFolder("f7fc9c56-1412-404e-9841-2ef3244b05bc")]
            public virtual RxDemoAppRepositoryFolders.RxTabImageBasedFolder RxTabImageBased
            {
                get { return _rxtabimagebased; }
            }

            /// <summary>
            /// The RxTabUIElements folder.
            /// </summary>
            [RepositoryFolder("17ef63d9-9aa3-4d8b-8498-31d59da08e3f")]
            public virtual RxDemoAppRepositoryFolders.RxTabUIElementsFolder RxTabUIElements
            {
                get { return _rxtabuielements; }
            }

            /// <summary>
            /// The RxTabUpload folder.
            /// </summary>
            [RepositoryFolder("a0534421-3542-41a0-a443-2d9d736c93fd")]
            public virtual RxDemoAppRepositoryFolders.RxTabUploadFolder RxTabUpload
            {
                get { return _rxtabupload; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("8e93b5e8-cb7a-4017-9262-1efe762e9148")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "8e93b5e8-cb7a-4017-9262-1efe762e9148", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "d5363b57-7196-4eef-8860-4f8719a330f5");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", "", 30000, null, "e611ec9d-3e50-42c7-be10-30b0ba70a75c");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", "", 30000, null, "f8b8809c-1806-4f75-b98b-069512f0fc4d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e93b5e8-cb7a-4017-9262-1efe762e9148")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e93b5e8-cb7a-4017-9262-1efe762e9148")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("d5363b57-7196-4eef-8860-4f8719a330f5")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("d5363b57-7196-4eef-8860-4f8719a330f5")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("e611ec9d-3e50-42c7-be10-30b0ba70a75c")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("e611ec9d-3e50-42c7-be10-30b0ba70a75c")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("f8b8809c-1806-4f75-b98b-069512f0fc4d")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("f8b8809c-1806-4f75-b98b-069512f0fc4d")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("794cc092-b05f-4699-ba2e-d58d3f1456b3")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _rohangcmale23testingInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "794cc092-b05f-4699-ba2e-d58d3f1456b3", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "3d69f58e-3c8e-410b-ae3e-286205367915");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname='rdbMale']", "", 30000, null, "c12b94ac-fbe4-4e4a-8729-0bae7cea848b");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "de018ff5-73ea-4807-9be2-557f0e42a010");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "22523d2b-6d6e-4856-b8a9-4146a9600a90");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "af654cfb-6426-4e42-bfa1-7b788a162553");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", "", 30000, null, "41f915c8-6f61-435f-8280-6d7b985286d6");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", "", 30000, null, "0c24e224-40c7-42e2-a64d-3908896ab4b5");
                _rohangcmale23testingInfo = new RepoItemInfo(this, "RohanGCMale23Testing", "list[@controlname='lstPersonList']/?/?/listitem[@accessiblename>'Rohan G C (male, 23) Test']", "", 30000, null, "7f918601-b2fa-401d-a63d-7474b7a45d69");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "abfbc8bd-8283-49ce-9665-3bd628756c9d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("794cc092-b05f-4699-ba2e-d58d3f1456b3")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("794cc092-b05f-4699-ba2e-d58d3f1456b3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("3d69f58e-3c8e-410b-ae3e-286205367915")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("3d69f58e-3c8e-410b-ae3e-286205367915")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("c12b94ac-fbe4-4e4a-8729-0bae7cea848b")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("c12b94ac-fbe4-4e4a-8729-0bae7cea848b")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("de018ff5-73ea-4807-9be2-557f0e42a010")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("de018ff5-73ea-4807-9be2-557f0e42a010")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("22523d2b-6d6e-4856-b8a9-4146a9600a90")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("22523d2b-6d6e-4856-b8a9-4146a9600a90")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("af654cfb-6426-4e42-bfa1-7b788a162553")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("af654cfb-6426-4e42-bfa1-7b788a162553")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("41f915c8-6f61-435f-8280-6d7b985286d6")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("41f915c8-6f61-435f-8280-6d7b985286d6")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("0c24e224-40c7-42e2-a64d-3908896ab4b5")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("0c24e224-40c7-42e2-a64d-3908896ab4b5")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The RohanGCMale23Testing item.
            /// </summary>
            [RepositoryItem("7f918601-b2fa-401d-a63d-7474b7a45d69")]
            public virtual Ranorex.ListItem RohanGCMale23Testing
            {
                get
                {
                    return _rohangcmale23testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The RohanGCMale23Testing item info.
            /// </summary>
            [RepositoryItemInfo("7f918601-b2fa-401d-a63d-7474b7a45d69")]
            public virtual RepoItemInfo RohanGCMale23TestingInfo
            {
                get
                {
                    return _rohangcmale23testingInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("abfbc8bd-8283-49ce-9665-3bd628756c9d")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("abfbc8bd-8283-49ce-9665-3bd628756c9d")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabImageBasedFolder folder.
        /// </summary>
        [RepositoryFolder("f7fc9c56-1412-404e-9841-2ef3244b05bc")]
        public partial class RxTabImageBasedFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chkshowimageInfo;
            RepoItemInfo _monthcalendar1Info;
            RepoItemInfo _thecatInfo;

            /// <summary>
            /// Creates a new RxTabImageBased  folder.
            /// </summary>
            public RxTabImageBasedFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabImageBased", "?/?/tabpage[@controlname='RxTabImageBased']", parentFolder, 30000, null, false, "f7fc9c56-1412-404e-9841-2ef3244b05bc", "")
            {
                _chkshowimageInfo = new RepoItemInfo(this, "ChkShowImage", "checkbox[@controlname='chkShowImage']", "", 30000, null, "0e738ea1-f4f2-4c37-b79c-6b1d32d6b45b");
                _monthcalendar1Info = new RepoItemInfo(this, "MonthCalendar1", "datetime[@controlname='monthCalendar1']", "", 30000, null, "b040122b-b733-4f84-aed7-b86520b0c4a1");
                _thecatInfo = new RepoItemInfo(this, "TheCat", "picture[@controlname='TheCat']", "", 30000, null, "33037f1c-d2d4-4cbf-8c91-798a4b1308c5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7fc9c56-1412-404e-9841-2ef3244b05bc")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7fc9c56-1412-404e-9841-2ef3244b05bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("0e738ea1-f4f2-4c37-b79c-6b1d32d6b45b")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("0e738ea1-f4f2-4c37-b79c-6b1d32d6b45b")]
            public virtual RepoItemInfo ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The MonthCalendar1 item.
            /// </summary>
            [RepositoryItem("b040122b-b733-4f84-aed7-b86520b0c4a1")]
            public virtual Ranorex.DateTime MonthCalendar1
            {
                get
                {
                    return _monthcalendar1Info.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The MonthCalendar1 item info.
            /// </summary>
            [RepositoryItemInfo("b040122b-b733-4f84-aed7-b86520b0c4a1")]
            public virtual RepoItemInfo MonthCalendar1Info
            {
                get
                {
                    return _monthcalendar1Info;
                }
            }

            /// <summary>
            /// The TheCat item.
            /// </summary>
            [RepositoryItem("33037f1c-d2d4-4cbf-8c91-798a4b1308c5")]
            public virtual Ranorex.Picture TheCat
            {
                get
                {
                    return _thecatInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The TheCat item info.
            /// </summary>
            [RepositoryItemInfo("33037f1c-d2d4-4cbf-8c91-798a4b1308c5")]
            public virtual RepoItemInfo TheCatInfo
            {
                get
                {
                    return _thecatInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUIElementsFolder folder.
        /// </summary>
        [RepositoryFolder("17ef63d9-9aa3-4d8b-8498-31d59da08e3f")]
        public partial class RxTabUIElementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _handsonapplicationtopicsInfo;
            RepoItemInfo _linedownInfo;
            RepoItemInfo _pnlcolourpanelInfo;
            RepoItemInfo _downInfo;
            RepoItemInfo _rdbgreenlightInfo;
            RepoItemInfo _rdbredlightInfo;
            RepoItemInfo _departmentrow7Info;
            RepoItemInfo _ranorexrecorderInfo;
            RepoItemInfo _ranorexstudiofundamentalsInfo;

            /// <summary>
            /// Creates a new RxTabUIElements  folder.
            /// </summary>
            public RxTabUIElementsFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUIElements", "?/?/tabpage[@controlname='RxTabUIElements']", parentFolder, 30000, null, false, "17ef63d9-9aa3-4d8b-8498-31d59da08e3f", "")
            {
                _handsonapplicationtopicsInfo = new RepoItemInfo(this, "HandsOnApplicationTopics", ".//list[@controlname='lstTestBox']/list[@accessiblename='Image-based automation']/listitem[@accessiblename>'Hands-on application topi']", "", 30000, null, "186320b4-103f-4698-a96b-f7a686177c20");
                _linedownInfo = new RepoItemInfo(this, "LineDown", "?/?/scrollbar[@controlname='vertScrollBar']/button[@accessiblename='Line down']", "", 30000, null, "98770d01-83c3-4439-9bed-b78bda9db8f2");
                _pnlcolourpanelInfo = new RepoItemInfo(this, "PnlColourPanel", "container[@controlname='grpBox']/?/?/container[@controlname='pnlColourPanel']", "", 30000, null, "7e391e1d-f0e3-4fda-885e-e49023cc01b8");
                _downInfo = new RepoItemInfo(this, "Down", "container[@controlname='grpBox']/?/?/list[@controlname='lstTestBox']/?/?/button[@text='Down']", "", 30000, null, "c07fb91b-d178-4b17-aa57-b1120360743f");
                _rdbgreenlightInfo = new RepoItemInfo(this, "RdbGreenLight", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbGreenLight']", "", 30000, null, "e0311cb8-f915-4001-96f2-ade65dab6c77");
                _rdbredlightInfo = new RepoItemInfo(this, "RdbRedLight", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbRedLight']", "", 30000, null, "e50b0357-d097-4130-98ef-181be75de7aa");
                _departmentrow7Info = new RepoItemInfo(this, "DepartmentRow7", "table[@controlname='dataGridView1']/?/?/cell[@accessiblename='Department Row 7']", "", 30000, null, "3f3bd53f-db7a-4f14-8f10-ac2c88dca0a7");
                _ranorexrecorderInfo = new RepoItemInfo(this, "RanorexRecorder", "tree[@controlname='treTestTreeView']//treeitem[@accessiblename='Ranorex Recorder']", "", 30000, null, "680b7b4a-860d-4324-9b77-e1224ab6884b");
                _ranorexstudiofundamentalsInfo = new RepoItemInfo(this, "RanorexStudioFundamentals", "tree[@controlname='treTestTreeView']/?/?/treeitem[@accessiblename>'Ranorex Studio fundamenta']", "", 30000, null, "1a1b67ca-e8bb-448d-9149-412af0961af2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17ef63d9-9aa3-4d8b-8498-31d59da08e3f")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17ef63d9-9aa3-4d8b-8498-31d59da08e3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HandsOnApplicationTopics item.
            /// </summary>
            [RepositoryItem("186320b4-103f-4698-a96b-f7a686177c20")]
            public virtual Ranorex.ListItem HandsOnApplicationTopics
            {
                get
                {
                    return _handsonapplicationtopicsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The HandsOnApplicationTopics item info.
            /// </summary>
            [RepositoryItemInfo("186320b4-103f-4698-a96b-f7a686177c20")]
            public virtual RepoItemInfo HandsOnApplicationTopicsInfo
            {
                get
                {
                    return _handsonapplicationtopicsInfo;
                }
            }

            /// <summary>
            /// The LineDown item.
            /// </summary>
            [RepositoryItem("98770d01-83c3-4439-9bed-b78bda9db8f2")]
            public virtual Ranorex.Button LineDown
            {
                get
                {
                    return _linedownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LineDown item info.
            /// </summary>
            [RepositoryItemInfo("98770d01-83c3-4439-9bed-b78bda9db8f2")]
            public virtual RepoItemInfo LineDownInfo
            {
                get
                {
                    return _linedownInfo;
                }
            }

            /// <summary>
            /// The PnlColourPanel item.
            /// </summary>
            [RepositoryItem("7e391e1d-f0e3-4fda-885e-e49023cc01b8")]
            public virtual Ranorex.Container PnlColourPanel
            {
                get
                {
                    return _pnlcolourpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlColourPanel item info.
            /// </summary>
            [RepositoryItemInfo("7e391e1d-f0e3-4fda-885e-e49023cc01b8")]
            public virtual RepoItemInfo PnlColourPanelInfo
            {
                get
                {
                    return _pnlcolourpanelInfo;
                }
            }

            /// <summary>
            /// The Down item.
            /// </summary>
            [RepositoryItem("c07fb91b-d178-4b17-aa57-b1120360743f")]
            public virtual Ranorex.Button Down
            {
                get
                {
                    return _downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down item info.
            /// </summary>
            [RepositoryItemInfo("c07fb91b-d178-4b17-aa57-b1120360743f")]
            public virtual RepoItemInfo DownInfo
            {
                get
                {
                    return _downInfo;
                }
            }

            /// <summary>
            /// The RdbGreenLight item.
            /// </summary>
            [RepositoryItem("e0311cb8-f915-4001-96f2-ade65dab6c77")]
            public virtual Ranorex.RadioButton RdbGreenLight
            {
                get
                {
                    return _rdbgreenlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbGreenLight item info.
            /// </summary>
            [RepositoryItemInfo("e0311cb8-f915-4001-96f2-ade65dab6c77")]
            public virtual RepoItemInfo RdbGreenLightInfo
            {
                get
                {
                    return _rdbgreenlightInfo;
                }
            }

            /// <summary>
            /// The RdbRedLight item.
            /// </summary>
            [RepositoryItem("e50b0357-d097-4130-98ef-181be75de7aa")]
            public virtual Ranorex.RadioButton RdbRedLight
            {
                get
                {
                    return _rdbredlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbRedLight item info.
            /// </summary>
            [RepositoryItemInfo("e50b0357-d097-4130-98ef-181be75de7aa")]
            public virtual RepoItemInfo RdbRedLightInfo
            {
                get
                {
                    return _rdbredlightInfo;
                }
            }

            /// <summary>
            /// The DepartmentRow7 item.
            /// </summary>
            [RepositoryItem("3f3bd53f-db7a-4f14-8f10-ac2c88dca0a7")]
            public virtual Ranorex.Cell DepartmentRow7
            {
                get
                {
                    return _departmentrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The DepartmentRow7 item info.
            /// </summary>
            [RepositoryItemInfo("3f3bd53f-db7a-4f14-8f10-ac2c88dca0a7")]
            public virtual RepoItemInfo DepartmentRow7Info
            {
                get
                {
                    return _departmentrow7Info;
                }
            }

            /// <summary>
            /// The RanorexRecorder item.
            /// </summary>
            [RepositoryItem("680b7b4a-860d-4324-9b77-e1224ab6884b")]
            public virtual Ranorex.TreeItem RanorexRecorder
            {
                get
                {
                    return _ranorexrecorderInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexRecorder item info.
            /// </summary>
            [RepositoryItemInfo("680b7b4a-860d-4324-9b77-e1224ab6884b")]
            public virtual RepoItemInfo RanorexRecorderInfo
            {
                get
                {
                    return _ranorexrecorderInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioFundamentals item.
            /// </summary>
            [RepositoryItem("1a1b67ca-e8bb-448d-9149-412af0961af2")]
            public virtual Ranorex.TreeItem RanorexStudioFundamentals
            {
                get
                {
                    return _ranorexstudiofundamentalsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioFundamentals item info.
            /// </summary>
            [RepositoryItemInfo("1a1b67ca-e8bb-448d-9149-412af0961af2")]
            public virtual RepoItemInfo RanorexStudioFundamentalsInfo
            {
                get
                {
                    return _ranorexstudiofundamentalsInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUploadFolder folder.
        /// </summary>
        [RepositoryFolder("a0534421-3542-41a0-a443-2d9d736c93fd")]
        public partial class RxTabUploadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _resetuploadInfo;
            RepoItemInfo _rbfastInfo;
            RepoItemInfo _btnstartuploadInfo;
            RepoItemInfo _lblfinishedInfo;

            /// <summary>
            /// Creates a new RxTabUpload  folder.
            /// </summary>
            public RxTabUploadFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUpload", "?/?/tabpage[@controlname='RxTabUpload']", parentFolder, 30000, null, false, "a0534421-3542-41a0-a443-2d9d736c93fd", "")
            {
                _resetuploadInfo = new RepoItemInfo(this, "ResetUpload", "?/?/element[@accessiblename='Reset upload']", "", 30000, null, "dca24137-f1b6-4ccc-90df-541625a1148c");
                _rbfastInfo = new RepoItemInfo(this, "RBFast", "?/?/radiobutton[@controlname='rBFast']", "", 30000, null, "43bc1eb6-536a-4d07-8f52-9c2739cffefd");
                _btnstartuploadInfo = new RepoItemInfo(this, "BtnStartUpload", "button[@controlname='btnStartUpload']", "", 30000, null, "b386ae54-deb8-47e8-95a9-d1d8486435fd");
                _lblfinishedInfo = new RepoItemInfo(this, "LblFinished", "text[@controlname='lblFinished']", "", 30000, null, "cd7ffbc6-1316-484a-b5eb-bf2e8ee4fa0d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0534421-3542-41a0-a443-2d9d736c93fd")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0534421-3542-41a0-a443-2d9d736c93fd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ResetUpload item.
            /// </summary>
            [RepositoryItem("dca24137-f1b6-4ccc-90df-541625a1148c")]
            public virtual Ranorex.Unknown ResetUpload
            {
                get
                {
                    return _resetuploadInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ResetUpload item info.
            /// </summary>
            [RepositoryItemInfo("dca24137-f1b6-4ccc-90df-541625a1148c")]
            public virtual RepoItemInfo ResetUploadInfo
            {
                get
                {
                    return _resetuploadInfo;
                }
            }

            /// <summary>
            /// The RBFast item.
            /// </summary>
            [RepositoryItem("43bc1eb6-536a-4d07-8f52-9c2739cffefd")]
            public virtual Ranorex.RadioButton RBFast
            {
                get
                {
                    return _rbfastInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RBFast item info.
            /// </summary>
            [RepositoryItemInfo("43bc1eb6-536a-4d07-8f52-9c2739cffefd")]
            public virtual RepoItemInfo RBFastInfo
            {
                get
                {
                    return _rbfastInfo;
                }
            }

            /// <summary>
            /// The BtnStartUpload item.
            /// </summary>
            [RepositoryItem("b386ae54-deb8-47e8-95a9-d1d8486435fd")]
            public virtual Ranorex.Button BtnStartUpload
            {
                get
                {
                    return _btnstartuploadInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnStartUpload item info.
            /// </summary>
            [RepositoryItemInfo("b386ae54-deb8-47e8-95a9-d1d8486435fd")]
            public virtual RepoItemInfo BtnStartUploadInfo
            {
                get
                {
                    return _btnstartuploadInfo;
                }
            }

            /// <summary>
            /// The LblFinished item.
            /// </summary>
            [RepositoryItem("cd7ffbc6-1316-484a-b5eb-bf2e8ee4fa0d")]
            public virtual Ranorex.Text LblFinished
            {
                get
                {
                    return _lblfinishedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblFinished item info.
            /// </summary>
            [RepositoryItemInfo("cd7ffbc6-1316-484a-b5eb-bf2e8ee4fa0d")]
            public virtual RepoItemInfo LblFinishedInfo
            {
                get
                {
                    return _lblfinishedInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("63c0b7d8-afc0-427c-bfea-2b74a03c1720")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testingInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "63c0b7d8-afc0-427c-bfea-2b74a03c1720", "")
            {
                _testingInfo = new RepoItemInfo(this, "Testing", "listitem[@text='Testing']", "listitem[@text='Testing']", 30000, null, "06908b58-b057-4b25-8f67-c598cd6abcb1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63c0b7d8-afc0-427c-bfea-2b74a03c1720")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63c0b7d8-afc0-427c-bfea-2b74a03c1720")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("06908b58-b057-4b25-8f67-c598cd6abcb1")]
            public virtual Ranorex.ListItem Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("06908b58-b057-4b25-8f67-c598cd6abcb1")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
